---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact:
        request_body:
          {
              "id": "ubuntu",
              "instances": 1,
              "cpus": 0.25,
              "mem": 32,
              "cmd": "python3 -m http.server 8080",
              "container": {
                "type": "DOCKER",
                "docker": {
                  "image": "python:3",
                  "privileged": true,
                  "network": "BRIDGE",
                  "portMappings": [
                    {
                      "containerPort": 8080,
                      "hostPort": 0
                    }
                  ]
                }
              },
              "healthChecks": [
                {
                  "protocol": "HTTP",
                  "portIndex": 0,
                  "path": "/",
                  "gracePeriodSeconds": 5,
                  "intervalSeconds": 20,
                  "maxConsecutiveFailures": 3
                }
              ]
        }
    - name: Kick off marathon
      uri: url=http://{{mesos_master}}:8080/v2/apps/}}
        method=PUT
        body='{{ request_body | to_json}}'
        HEADER_Content-Type="application/json"
        status_code=200,201,204