---

- hosts: 127.0.0.1
  connection: local
  vars:
    app_name: "ubuntu"
  tasks:
    - name: create json body
      template: src=templates/app.json.j2 dest=/var/tmp/templ.json

    - name: Kick off marathon
      uri: url=http://{{mesos_master}}:8080/v2/apps/{{app_name}}
        method=PUT
        body='{{ lookup("file", "/var/tmp/templ.json") }}'
        body_format=json
        status_code=200,201,204